-- MySQL Script generated by MySQL Workbench
-- Mon Dec  2 17:06:28 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`MarcaVeiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MarcaVeiculo` (
  `idMarcaVeiculo` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idMarcaVeiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ModeloVeiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ModeloVeiculo` (
  `idModeloVeiculo` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idModeloVeiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veiculo` (
  `idVeiculo` INT NOT NULL,
  `placa` VARCHAR(45) NULL,
  `marca` INT NOT NULL,
  `model` INT NOT NULL,
  PRIMARY KEY (`idVeiculo`),
  INDEX `fk_Veiculo_MarcaVeiculo1_idx` (`marca` ASC),
  INDEX `fk_Veiculo_ModeloVeiculo1_idx` (`model` ASC),
  CONSTRAINT `fk_Veiculo_MarcaVeiculo1`
    FOREIGN KEY (`marca`)
    REFERENCES `mydb`.`MarcaVeiculo` (`idMarcaVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veiculo_ModeloVeiculo1`
    FOREIGN KEY (`model`)
    REFERENCES `mydb`.`ModeloVeiculo` (`idModeloVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Unidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Unidade` (
  `idUnidade` INT NOT NULL,
  `valor` VARCHAR(45) NULL,
  PRIMARY KEY (`idUnidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoDeslocamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoDeslocamento` (
  `idTipoDeslocamento` INT NOT NULL,
  `valor` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoDeslocamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Situacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Situacao` (
  `idSituacao` INT NOT NULL,
  `valor` VARCHAR(45) NULL,
  PRIMARY KEY (`idSituacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `idPessoa` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Motorista` (
  `idMotorista` INT NOT NULL,
  `numCNH` VARCHAR(45) NULL,
  `pessoa` INT NOT NULL,
  PRIMARY KEY (`idMotorista`),
  INDEX `fk_Motorista_Pessoa1_idx` (`pessoa` ASC),
  CONSTRAINT `fk_Motorista_Pessoa1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Viagem` (
  `idViagem` INT NOT NULL,
  `dataSolicitacao` VARCHAR(45) NULL,
  `qtdPassageiros` VARCHAR(45) NULL,
  `vlCustoEstadia` VARCHAR(45) NULL,
  `vlCustoEstVeiculo` VARCHAR(45) NULL,
  `veiculo` INT NOT NULL,
  `unidade` INT NOT NULL,
  `tipoDeslocamento` INT NOT NULL,
  `situacao` INT NOT NULL,
  `motorista` INT NOT NULL,
  PRIMARY KEY (`idViagem`),
  INDEX `fk_Viagem_Veiculo_idx` (`veiculo` ASC),
  INDEX `fk_Viagem_Unidade1_idx` (`unidade` ASC),
  INDEX `fk_Viagem_TipoDeslocamento1_idx` (`tipoDeslocamento` ASC),
  INDEX `fk_Viagem_Situacao1_idx` (`situacao` ASC),
  INDEX `fk_Viagem_Motorista1_idx` (`motorista` ASC),
  CONSTRAINT `fk_Viagem_Veiculo`
    FOREIGN KEY (`veiculo`)
    REFERENCES `mydb`.`Veiculo` (`idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viagem_Unidade1`
    FOREIGN KEY (`unidade`)
    REFERENCES `mydb`.`Unidade` (`idUnidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viagem_TipoDeslocamento1`
    FOREIGN KEY (`tipoDeslocamento`)
    REFERENCES `mydb`.`TipoDeslocamento` (`idTipoDeslocamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viagem_Situacao1`
    FOREIGN KEY (`situacao`)
    REFERENCES `mydb`.`Situacao` (`idSituacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viagem_Motorista1`
    FOREIGN KEY (`motorista`)
    REFERENCES `mydb`.`Motorista` (`idMotorista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passageiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passageiro` (
  `idPassageiro` INT NOT NULL,
  `sexo` VARCHAR(45) NULL,
  `pessoa` INT NOT NULL,
  PRIMARY KEY (`idPassageiro`),
  INDEX `fk_Passageiro_Pessoa1_idx` (`pessoa` ASC),
  CONSTRAINT `fk_Passageiro_Pessoa1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seguradora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seguradora` (
  `idSeguradora` INT NOT NULL,
  `endereco` VARCHAR(45) NULL,
  `pessoa` INT NOT NULL,
  PRIMARY KEY (`idSeguradora`),
  INDEX `fk_Seguradora_Pessoa1_idx` (`pessoa` ASC),
  CONSTRAINT `fk_Seguradora_Pessoa1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PessoaFisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PessoaFisica` (
  `idPessoaFisica` INT NOT NULL,
  `rg` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `pessoa` INT NOT NULL,
  PRIMARY KEY (`idPessoaFisica`),
  INDEX `fk_PessoaFisica_Pessoa1_idx` (`pessoa` ASC),
  CONSTRAINT `fk_PessoaFisica_Pessoa1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PessoaJuridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PessoaJuridica` (
  `idPessoaJuridica` INT NOT NULL,
  `razaoSocial` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `pessoa` INT NOT NULL,
  PRIMARY KEY (`idPessoaJuridica`),
  INDEX `fk_PessoaJuridica_Pessoa1_idx` (`pessoa` ASC),
  CONSTRAINT `fk_PessoaJuridica_Pessoa1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PassageiroViagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PassageiroViagem` (
  `Passageiro_idPassageiro` INT NOT NULL,
  `Viagem_idViagem` INT NOT NULL,
  PRIMARY KEY (`Passageiro_idPassageiro`, `Viagem_idViagem`),
  INDEX `fk_Passageiro_has_Viagem_Viagem1_idx` (`Viagem_idViagem` ASC),
  INDEX `fk_Passageiro_has_Viagem_Passageiro1_idx` (`Passageiro_idPassageiro` ASC),
  CONSTRAINT `fk_Passageiro_has_Viagem_Passageiro1`
    FOREIGN KEY (`Passageiro_idPassageiro`)
    REFERENCES `mydb`.`Passageiro` (`idPassageiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Passageiro_has_Viagem_Viagem1`
    FOREIGN KEY (`Viagem_idViagem`)
    REFERENCES `mydb`.`Viagem` (`idViagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
